package:
  name: ros-humble-ros-gz-sim-demos
  version: 0.244.9
source:
  git_url: https://github.com/ros2-gbp/ros_ign-release.git
  git_rev: release/humble/ros_gz_sim_demos/0.244.9-1
  folder: ros-humble-ros-gz-sim-demos/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
  run:
    - libignition-gazebo6
    - python
    - ros-humble-image-transport-plugins
    - ros-humble-robot-state-publisher
    - ros-humble-ros-gz-bridge
    - ros-humble-ros-gz-image
    - ros-humble-ros-gz-sim
    - ros-humble-ros-workspace
    - ros-humble-rqt-image-view
    - ros-humble-rqt-plot
    - ros-humble-rqt-topic
    - ros-humble-rviz2
    - ros-humble-sdformat-urdf
    - ros-humble-xacro
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
