package:
  name: ros-humble-rsl
  version: 0.2.1
source:
  git_url: https://github.com/PickNikRobotics/RSL-release.git
  git_rev: release/humble/rsl/0.2.1-1
  folder: ros-humble-rsl/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - git
    - sel(build_platform != target_platform): doxygen
  host:
    - clang-tools
    - doxygen
    - eigen
    - fmt
    - python
    - ros-humble-ament-cmake
    - ros-humble-rclcpp
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-tcb-span
    - ros-humble-tl-expected
    - ros2-distro-mutex 0.1 humble
    - sel(build_platform == target_platform): doxygen
  run:
    - eigen
    - fmt
    - python
    - ros-humble-rclcpp
    - ros-humble-ros-workspace
    - ros-humble-tcb-span
    - ros-humble-tl-expected
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
