package:
  name: ros-humble-moveit-ros-visualization
  version: 2.5.4
source:
  git_url: https://github.com/moveit/moveit2-release.git
  git_rev: release/humble/moveit_ros_visualization/2.5.4-1
  folder: ros-humble-moveit-ros-visualization/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): pkg-config
    - sel(linux): "{{ cdt('mesa-libgl-devel') }}"
    - sel(linux): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - eigen
    - python
    - qt-main
    - ros-humble-ament-cmake
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-class-loader
    - ros-humble-geometric-shapes
    - ros-humble-interactive-markers
    - ros-humble-moveit-common
    - ros-humble-moveit-ros-planning-interface
    - ros-humble-moveit-ros-robot-interaction
    - ros-humble-moveit-ros-warehouse
    - ros-humble-object-recognition-msgs
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-rclpy
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rviz2
    - ros-humble-tf2-eigen
    - ros2-distro-mutex 0.1 humble
    - sel(build_platform == target_platform): pkg-config
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - python
    - ros-humble-geometric-shapes
    - ros-humble-interactive-markers
    - ros-humble-moveit-common
    - ros-humble-moveit-ros-planning-interface
    - ros-humble-moveit-ros-robot-interaction
    - ros-humble-moveit-ros-warehouse
    - ros-humble-object-recognition-msgs
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-rclpy
    - ros-humble-ros-workspace
    - ros-humble-rviz2
    - ros-humble-tf2-eigen
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
