package:
  name: ros-humble-ros-gz-image
  version: 0.244.9
source:
  git_url: https://github.com/ros2-gbp/ros_ign-release.git
  git_rev: release/humble/ros_gz_image/0.244.9-1
  folder: ros-humble-ros-gz-image/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake 3.23
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): pkg-config
  host:
    - libignition-msgs8
    - libignition-transport11
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-image-transport
    - ros-humble-rclcpp
    - ros-humble-ros-environment
    - ros-humble-ros-gz-bridge
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros2-distro-mutex 0.1 humble
    - sel(build_platform == target_platform): pkg-config
  run:
    - libignition-msgs8
    - libignition-transport11
    - python
    - ros-humble-image-transport
    - ros-humble-rclcpp
    - ros-humble-ros-gz-bridge
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
