# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: ros-humble-rosidl-runtime-cpp
  version: 3.1.6
source:
  git: https://github.com/ros2-gbp/rosidl-release.git
  tag: release/humble/rosidl_runtime_cpp/3.1.6-1
  target_directory: ros-humble-rosidl-runtime-cpp/src/work
  patches:
    - patch/ros-humble-rosidl-runtime-cpp.patch

build:
  script: ${{ '$RECIPE_DIR/build_ament_cmake.sh' if unix or wasm32 else '%RECIPE_DIR%\\bld_ament_cmake.bat' }}
  number: 14
  post_process:
    - files:
        - '*.pc'
      regex: (?:-L|-I)?"?([^;\s]+/sysroot/)
      replacement: $$(CONDA_BUILD_SYSROOT_S)
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/sysroot)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
    - files:
        - '*.cmake'
      regex: ([^;\s"]+/MacOSX\d*\.?\d*\.sdk)
      replacement: $$ENV{CONDA_BUILD_SYSROOT}
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - if: target_platform!='emscripten-wasm32'
      then:
        - ${{ stdlib('c') }}
    - ninja
    - python
    - setuptools
    - git
    - git-lfs
    - if: unix
      then:
        - patch
        - make
        - coreutils
    - if: win
      then:
        - m2-patch
    - if: osx
      then:
        - tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
    - cmake
    - cython
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - if: build_platform == target_platform
      then:
        - pkg-config
    - numpy
    - pip
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-runtime-c
    - ros2-distro-mutex 0.7.* humble_*
  run:
    - python
    - ros-humble-ament-cmake
    - ros-humble-ros-workspace
    - ros-humble-rosidl-runtime-c
    - ros2-distro-mutex 0.7.* humble_*
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
