jobs:
  stage_0_job_0:
    name: nav2-bringup apriltag-draw apriltag-mit apriltag-detector-umich
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-nav2-bringup ros-humble-apriltag-draw ros-humble-apriltag-mit
        ros-humble-apriltag-detector-umich
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-nav2-bringup ros-humble-apriltag-draw ros-humble-apriltag-mit
          ros-humble-apriltag-detector-umich
        BUILD_TARGET: linux-aarch64
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_1_job_1:
    name: apriltag-detector-mit
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-apriltag-detector-mit
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-apriltag-detector-mit
        BUILD_TARGET: linux-aarch64
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
name: build_linux_aarch64
on:
  push:
    branches:
    - buildbranch_linux_aarch64
