jobs:
  stage_0_job_0:
    name: ament-uncrustify
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-ament-uncrustify
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ament-uncrustify
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_0_job_1:
    name: ament-cmake-copyright
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-ament-cmake-copyright
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ament-cmake-copyright
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_0_job_2:
    name: launch-yaml
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-launch-yaml
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-launch-yaml
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_0_job_3:
    name: launch-xml
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-launch-xml
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-launch-xml
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_0_job_4:
    name: pybind11-vendor
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-pybind11-vendor
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-pybind11-vendor
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_1_job_5:
    name: ament-cmake-uncrustify
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    - stage_0_job_1
    - stage_0_job_2
    - stage_0_job_3
    - stage_0_job_4
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-ament-cmake-uncrustify
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ament-cmake-uncrustify
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_1_job_6:
    name: ament-cmake-pep257
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    - stage_0_job_1
    - stage_0_job_2
    - stage_0_job_3
    - stage_0_job_4
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-ament-cmake-pep257
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ament-cmake-pep257
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_1_job_7:
    name: ament-cmake-flake8
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    - stage_0_job_1
    - stage_0_job_2
    - stage_0_job_3
    - stage_0_job_4
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-ament-cmake-flake8
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ament-cmake-flake8
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_1_job_8:
    name: ament-cmake-cpplint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    - stage_0_job_1
    - stage_0_job_2
    - stage_0_job_3
    - stage_0_job_4
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-ament-cmake-cpplint
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ament-cmake-cpplint
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_1_job_9:
    name: ament-cmake-cppcheck
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    - stage_0_job_1
    - stage_0_job_2
    - stage_0_job_3
    - stage_0_job_4
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-ament-cmake-cppcheck
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ament-cmake-cppcheck
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_1_job_10:
    name: launch-testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    - stage_0_job_1
    - stage_0_job_2
    - stage_0_job_3
    - stage_0_job_4
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-launch-testing
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-launch-testing
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_2_job_11:
    name: ament-lint-common
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_1_job_5
    - stage_1_job_6
    - stage_1_job_7
    - stage_1_job_8
    - stage_1_job_9
    - stage_1_job_10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-ament-lint-common
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ament-lint-common
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_3_job_12:
    name: python-cmake-module
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_2_job_11
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-python-cmake-module
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-python-cmake-module
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_3_job_13:
    name: ament-cmake-ros
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_2_job_11
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-ament-cmake-ros
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ament-cmake-ros
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_3_job_14:
    name: rosidl-adapter
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_2_job_11
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-adapter
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-adapter
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_3_job_15:
    name: rosidl-typesupport-interface
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_2_job_11
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-typesupport-interface
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-typesupport-interface
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_3_job_16:
    name: rmw-implementation-cmake
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_2_job_11
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rmw-implementation-cmake
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rmw-implementation-cmake
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_3_job_17:
    name: ament-index-cpp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_2_job_11
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-ament-index-cpp
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ament-index-cpp
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_3_job_18:
    name: spdlog-vendor
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_2_job_11
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-spdlog-vendor
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-spdlog-vendor
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_4_job_19:
    name: launch-testing-ament-cmake
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_3_job_12
    - stage_3_job_13
    - stage_3_job_14
    - stage_3_job_15
    - stage_3_job_16
    - stage_3_job_17
    - stage_3_job_18
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-launch-testing-ament-cmake
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-launch-testing-ament-cmake
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_4_job_20:
    name: rosidl-parser
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_3_job_12
    - stage_3_job_13
    - stage_3_job_14
    - stage_3_job_15
    - stage_3_job_16
    - stage_3_job_17
    - stage_3_job_18
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-parser
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-parser
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_4_job_21:
    name: tracetools
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_3_job_12
    - stage_3_job_13
    - stage_3_job_14
    - stage_3_job_15
    - stage_3_job_16
    - stage_3_job_17
    - stage_3_job_18
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-tracetools
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-tracetools
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_5_job_22:
    name: rcutils
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_4_job_19
    - stage_4_job_20
    - stage_4_job_21
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rcutils
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rcutils
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_5_job_23:
    name: rosidl-cmake
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_4_job_19
    - stage_4_job_20
    - stage_4_job_21
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-cmake
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-cmake
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_6_job_24:
    name: rosidl-runtime-c
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_5_job_22
    - stage_5_job_23
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-runtime-c
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-runtime-c
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_6_job_25:
    name: rcpputils
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_5_job_22
    - stage_5_job_23
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rcpputils
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rcpputils
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_6_job_26:
    name: wasm-cpp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_5_job_22
    - stage_5_job_23
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-wasm-cpp
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-wasm-cpp
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_7_job_27:
    name: rosidl-typesupport-introspection-c
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_6_job_24
    - stage_6_job_25
    - stage_6_job_26
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-typesupport-introspection-c
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-typesupport-introspection-c
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_7_job_28:
    name: rosidl-runtime-cpp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_6_job_24
    - stage_6_job_25
    - stage_6_job_26
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-runtime-cpp
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-runtime-cpp
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_7_job_29:
    name: rosidl-generator-c
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_6_job_24
    - stage_6_job_25
    - stage_6_job_26
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-generator-c
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-generator-c
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_7_job_30:
    name: rmw
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_6_job_24
    - stage_6_job_25
    - stage_6_job_26
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rmw
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rmw
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_7_job_31:
    name: libyaml-vendor
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_6_job_24
    - stage_6_job_25
    - stage_6_job_26
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-libyaml-vendor
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-libyaml-vendor
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_7_job_32:
    name: rcl-logging-interface
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_6_job_24
    - stage_6_job_25
    - stage_6_job_26
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rcl-logging-interface
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rcl-logging-interface
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_8_job_33:
    name: rosidl-typesupport-introspection-cpp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_7_job_27
    - stage_7_job_28
    - stage_7_job_29
    - stage_7_job_30
    - stage_7_job_31
    - stage_7_job_32
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-typesupport-introspection-cpp
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-typesupport-introspection-cpp
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_8_job_34:
    name: rosidl-typesupport-c
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_7_job_27
    - stage_7_job_28
    - stage_7_job_29
    - stage_7_job_30
    - stage_7_job_31
    - stage_7_job_32
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-typesupport-c
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-typesupport-c
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_8_job_35:
    name: rosidl-generator-cpp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_7_job_27
    - stage_7_job_28
    - stage_7_job_29
    - stage_7_job_30
    - stage_7_job_31
    - stage_7_job_32
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-generator-cpp
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-generator-cpp
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_8_job_36:
    name: rcl-yaml-param-parser
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_7_job_27
    - stage_7_job_28
    - stage_7_job_29
    - stage_7_job_30
    - stage_7_job_31
    - stage_7_job_32
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rcl-yaml-param-parser
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rcl-yaml-param-parser
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_8_job_37:
    name: rcl-logging-spdlog
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_7_job_27
    - stage_7_job_28
    - stage_7_job_29
    - stage_7_job_30
    - stage_7_job_31
    - stage_7_job_32
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rcl-logging-spdlog
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rcl-logging-spdlog
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_9_job_38:
    name: rosidl-typesupport-cpp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_8_job_33
    - stage_8_job_34
    - stage_8_job_35
    - stage_8_job_36
    - stage_8_job_37
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-typesupport-cpp
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-typesupport-cpp
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_9_job_39:
    name: rosidl-generator-rs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_8_job_33
    - stage_8_job_34
    - stage_8_job_35
    - stage_8_job_36
    - stage_8_job_37
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-generator-rs
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-generator-rs
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_9_job_40:
    name: rosidl-generator-py
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_8_job_33
    - stage_8_job_34
    - stage_8_job_35
    - stage_8_job_36
    - stage_8_job_37
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-generator-py
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-generator-py
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_10_job_41:
    name: rosidl-default-runtime
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_9_job_38
    - stage_9_job_39
    - stage_9_job_40
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-default-runtime
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-default-runtime
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_10_job_42:
    name: rosidl-default-generators
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_9_job_38
    - stage_9_job_39
    - stage_9_job_40
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosidl-default-generators
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-default-generators
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_11_job_43:
    name: builtin-interfaces
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_10_job_41
    - stage_10_job_42
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-builtin-interfaces
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-builtin-interfaces
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_11_job_44:
    name: unique-identifier-msgs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_10_job_41
    - stage_10_job_42
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-unique-identifier-msgs
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-unique-identifier-msgs
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_11_job_45:
    name: lifecycle-msgs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_10_job_41
    - stage_10_job_42
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-lifecycle-msgs
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-lifecycle-msgs
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_12_job_46:
    name: std-msgs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_11_job_43
    - stage_11_job_44
    - stage_11_job_45
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-std-msgs
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-std-msgs
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_12_job_47:
    name: action-msgs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_11_job_43
    - stage_11_job_44
    - stage_11_job_45
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-action-msgs
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-action-msgs
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_12_job_48:
    name: rcl-interfaces
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_11_job_43
    - stage_11_job_44
    - stage_11_job_45
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rcl-interfaces
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rcl-interfaces
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_12_job_49:
    name: statistics-msgs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_11_job_43
    - stage_11_job_44
    - stage_11_job_45
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-statistics-msgs
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-statistics-msgs
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_12_job_50:
    name: rosgraph-msgs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_11_job_43
    - stage_11_job_44
    - stage_11_job_45
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rosgraph-msgs
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosgraph-msgs
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_13_job_51:
    name: dynmsg
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_12_job_46
    - stage_12_job_47
    - stage_12_job_48
    - stage_12_job_49
    - stage_12_job_50
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-dynmsg
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-dynmsg
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_13_job_52:
    name: test-msgs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_12_job_46
    - stage_12_job_47
    - stage_12_job_48
    - stage_12_job_49
    - stage_12_job_50
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-test-msgs
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-test-msgs
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_13_job_53:
    name: example-interfaces
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_12_job_46
    - stage_12_job_47
    - stage_12_job_48
    - stage_12_job_49
    - stage_12_job_50
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-example-interfaces
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-example-interfaces
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_14_job_54:
    name: rmw-wasm-cpp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_13_job_51
    - stage_13_job_52
    - stage_13_job_53
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rmw-wasm-cpp
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rmw-wasm-cpp
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_15_job_55:
    name: rmw-implementation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_14_job_54
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rmw-implementation
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rmw-implementation
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_16_job_56:
    name: rcl
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_15_job_55
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rcl
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rcl
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_17_job_57:
    name: rcl-lifecycle
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_16_job_56
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rcl-lifecycle
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rcl-lifecycle
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_17_job_58:
    name: rcl-action
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_16_job_56
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rcl-action
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rcl-action
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_17_job_59:
    name: libstatistics-collector
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_16_job_56
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-libstatistics-collector
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-libstatistics-collector
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_18_job_60:
    name: rclpy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_17_job_57
    - stage_17_job_58
    - stage_17_job_59
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rclpy
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rclpy
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_18_job_61:
    name: rclcpp
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_17_job_57
    - stage_17_job_58
    - stage_17_job_59
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rclcpp
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rclcpp
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_19_job_62:
    name: rclcpp-action
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_18_job_60
    - stage_18_job_61
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rclcpp-action
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rclcpp-action
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_19_job_63:
    name: test-wasm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_18_job_60
    - stage_18_job_61
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-test-wasm
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-test-wasm
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
  stage_20_job_64:
    name: rclc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs:
    - stage_19_job_62
    - stage_19_job_63
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-rclc
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rclc
        BUILD_TARGET: emscripten-wasm32
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
name: build_emscripten_wasm32
on:
  push:
    branches:
    - buildbranch_emscripten
