jobs:
  stage_0_job_0:
    name: rosidl-typesupport-fastrtps-cpp urdf ros2-control-test-assets qt-gui-cpp
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rosidl-typesupport-fastrtps-cpp ros-humble-urdf ros-humble-ros2-control-test-assets
        ros-humble-qt-gui-cpp
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-typesupport-fastrtps-cpp ros-humble-urdf
          ros-humble-ros2-control-test-assets ros-humble-qt-gui-cpp
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_1_job_1:
    name: rosidl-typesupport-fastrtps-c kdl-parser rosidl-typesupport-c
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rosidl-typesupport-fastrtps-c ros-humble-kdl-parser ros-humble-rosidl-typesupport-c
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-typesupport-fastrtps-c ros-humble-kdl-parser
          ros-humble-rosidl-typesupport-c
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_2_job_2:
    name: rosidl-typesupport-cpp rosidl-generator-py rosidl-default-runtime rosidl-default-generators
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_1_job_1
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rosidl-typesupport-cpp ros-humble-rosidl-generator-py
        ros-humble-rosidl-default-runtime ros-humble-rosidl-default-generators
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rosidl-typesupport-cpp ros-humble-rosidl-generator-py
          ros-humble-rosidl-default-runtime ros-humble-rosidl-default-generators
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_3_job_3:
    name: unique-identifier-msgs builtin-interfaces rmw-dds-common lifecycle-msgs
      std-srvs
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_2_job_2
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-unique-identifier-msgs ros-humble-builtin-interfaces
        ros-humble-rmw-dds-common ros-humble-lifecycle-msgs ros-humble-std-srvs
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-unique-identifier-msgs ros-humble-builtin-interfaces
          ros-humble-rmw-dds-common ros-humble-lifecycle-msgs ros-humble-std-srvs
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_4_job_4:
    name: action-msgs rmw-fastrtps-shared-cpp rmw-connextdds-common rmw-cyclonedds-cpp
      rcl-interfaces
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_3_job_3
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-action-msgs ros-humble-rmw-fastrtps-shared-cpp ros-humble-rmw-connextdds-common
        ros-humble-rmw-cyclonedds-cpp ros-humble-rcl-interfaces
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-action-msgs ros-humble-rmw-fastrtps-shared-cpp
          ros-humble-rmw-connextdds-common ros-humble-rmw-cyclonedds-cpp ros-humble-rcl-interfaces
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_4_job_5:
    name: std-msgs statistics-msgs rosgraph-msgs rosbag2-interfaces controller-manager-msgs
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_3_job_3
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-std-msgs ros-humble-statistics-msgs ros-humble-rosgraph-msgs
        ros-humble-rosbag2-interfaces ros-humble-controller-manager-msgs
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-std-msgs ros-humble-statistics-msgs ros-humble-rosgraph-msgs
          ros-humble-rosbag2-interfaces ros-humble-controller-manager-msgs
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_4_job_6:
    name: pendulum-msgs
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_3_job_3
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-pendulum-msgs
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-pendulum-msgs
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_5_job_7:
    name: test-msgs rmw-connextdds composition-interfaces geometry-msgs bond
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_4_job_4
    - stage_4_job_5
    - stage_4_job_6
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-test-msgs ros-humble-rmw-connextdds ros-humble-composition-interfaces
        ros-humble-geometry-msgs ros-humble-bond
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-test-msgs ros-humble-rmw-connextdds ros-humble-composition-interfaces
          ros-humble-geometry-msgs ros-humble-bond
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_5_job_8:
    name: actionlib-msgs ros2cli-test-interfaces example-interfaces action-tutorials-interfaces
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_4_job_4
    - stage_4_job_5
    - stage_4_job_6
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-actionlib-msgs ros-humble-ros2cli-test-interfaces ros-humble-example-interfaces
        ros-humble-action-tutorials-interfaces
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-actionlib-msgs ros-humble-ros2cli-test-interfaces
          ros-humble-example-interfaces ros-humble-action-tutorials-interfaces
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_6_job_9:
    name: rmw-fastrtps-dynamic-cpp rmw-fastrtps-cpp tf2 sensor-msgs rosidl-runtime-py
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_5_job_7
    - stage_5_job_8
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rmw-fastrtps-dynamic-cpp ros-humble-rmw-fastrtps-cpp
        ros-humble-tf2 ros-humble-sensor-msgs ros-humble-rosidl-runtime-py
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rmw-fastrtps-dynamic-cpp ros-humble-rmw-fastrtps-cpp
          ros-humble-tf2 ros-humble-sensor-msgs ros-humble-rosidl-runtime-py
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_6_job_10:
    name: tf2-msgs nav-msgs shape-msgs diagnostic-msgs trajectory-msgs
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_5_job_7
    - stage_5_job_8
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-tf2-msgs ros-humble-nav-msgs ros-humble-shape-msgs ros-humble-diagnostic-msgs
        ros-humble-trajectory-msgs
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-tf2-msgs ros-humble-nav-msgs ros-humble-shape-msgs
          ros-humble-diagnostic-msgs ros-humble-trajectory-msgs
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_6_job_11:
    name: octomap-msgs nav-2d-msgs ros-ign-interfaces
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_5_job_7
    - stage_5_job_8
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-octomap-msgs ros-humble-nav-2d-msgs ros-humble-ros-ign-interfaces
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-octomap-msgs ros-humble-nav-2d-msgs ros-humble-ros-ign-interfaces
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_7_job_12:
    name: rmw-implementation object-recognition-msgs visualization-msgs stereo-msgs
      sensor-msgs-py
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_6_job_9
    - stage_6_job_10
    - stage_6_job_11
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rmw-implementation ros-humble-object-recognition-msgs
        ros-humble-visualization-msgs ros-humble-stereo-msgs ros-humble-sensor-msgs-py
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rmw-implementation ros-humble-object-recognition-msgs
          ros-humble-visualization-msgs ros-humble-stereo-msgs ros-humble-sensor-msgs-py
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_7_job_13:
    name: map-msgs control-msgs dwb-msgs tf2-eigen-kdl cv-bridge
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_6_job_9
    - stage_6_job_10
    - stage_6_job_11
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-map-msgs ros-humble-control-msgs ros-humble-dwb-msgs
        ros-humble-tf2-eigen-kdl ros-humble-cv-bridge
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-map-msgs ros-humble-control-msgs ros-humble-dwb-msgs
          ros-humble-tf2-eigen-kdl ros-humble-cv-bridge
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_7_job_14:
    name: pcl-msgs image-geometry
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_6_job_9
    - stage_6_job_10
    - stage_6_job_11
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-pcl-msgs ros-humble-image-geometry
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-pcl-msgs ros-humble-image-geometry
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_8_job_15:
    name: rcl moveit-msgs common-interfaces vision-opencv
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_7_job_12
    - stage_7_job_13
    - stage_7_job_14
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rcl ros-humble-moveit-msgs ros-humble-common-interfaces
        ros-humble-vision-opencv
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rcl ros-humble-moveit-msgs ros-humble-common-interfaces
          ros-humble-vision-opencv
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_9_job_16:
    name: rcl-lifecycle rcl-action libstatistics-collector
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_8_job_15
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rcl-lifecycle ros-humble-rcl-action ros-humble-libstatistics-collector
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rcl-lifecycle ros-humble-rcl-action ros-humble-libstatistics-collector
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_10_job_17:
    name: rclpy rclcpp
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_9_job_16
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rclpy ros-humble-rclcpp
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rclpy ros-humble-rclcpp
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_11_job_18:
    name: launch-ros rclcpp-lifecycle ros2cli rosbag2-test-common tf2-py
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_10_job_17
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-launch-ros ros-humble-rclcpp-lifecycle ros-humble-ros2cli
        ros-humble-rosbag2-test-common ros-humble-tf2-py
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-launch-ros ros-humble-rclcpp-lifecycle ros-humble-ros2cli
          ros-humble-rosbag2-test-common ros-humble-tf2-py
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_11_job_19:
    name: rclcpp-components rclcpp-action urdfdom-py geometric-shapes laser-geometry
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_10_job_17
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rclcpp-components ros-humble-rclcpp-action ros-humble-urdfdom-py
        ros-humble-geometric-shapes ros-humble-laser-geometry
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rclcpp-components ros-humble-rclcpp-action ros-humble-urdfdom-py
          ros-humble-geometric-shapes ros-humble-laser-geometry
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_11_job_20:
    name: launch-param-builder rqt-gui behaviortree-cpp-v3 rqt-py-common camera-calibration-parsers
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_10_job_17
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-launch-param-builder ros-humble-rqt-gui ros-humble-behaviortree-cpp-v3
        ros-humble-rqt-py-common ros-humble-camera-calibration-parsers
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-launch-param-builder ros-humble-rqt-gui ros-humble-behaviortree-cpp-v3
          ros-humble-rqt-py-common ros-humble-camera-calibration-parsers
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_11_job_21:
    name: rqt-gui-cpp teleop-twist-keyboard filters dummy-sensors dummy-map-server
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_10_job_17
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rqt-gui-cpp ros-humble-teleop-twist-keyboard ros-humble-filters
        ros-humble-dummy-sensors ros-humble-dummy-map-server
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rqt-gui-cpp ros-humble-teleop-twist-keyboard ros-humble-filters
          ros-humble-dummy-sensors ros-humble-dummy-map-server
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_11_job_22:
    name: ros-ign-gazebo demo-nodes-py quality-of-service-demo-py intra-process-demo
      examples-rclpy-minimal-subscriber
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_10_job_17
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-ros-ign-gazebo ros-humble-demo-nodes-py ros-humble-quality-of-service-demo-py
        ros-humble-intra-process-demo ros-humble-examples-rclpy-minimal-subscriber
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ros-ign-gazebo ros-humble-demo-nodes-py ros-humble-quality-of-service-demo-py
          ros-humble-intra-process-demo ros-humble-examples-rclpy-minimal-subscriber
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_11_job_23:
    name: examples-rclpy-minimal-service examples-rclpy-minimal-publisher examples-rclpy-minimal-client
      examples-rclpy-minimal-action-server examples-rclpy-minimal-action-client
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_10_job_17
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-examples-rclpy-minimal-service ros-humble-examples-rclpy-minimal-publisher
        ros-humble-examples-rclpy-minimal-client ros-humble-examples-rclpy-minimal-action-server
        ros-humble-examples-rclpy-minimal-action-client
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-examples-rclpy-minimal-service ros-humble-examples-rclpy-minimal-publisher
          ros-humble-examples-rclpy-minimal-client ros-humble-examples-rclpy-minimal-action-server
          ros-humble-examples-rclpy-minimal-action-client
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_11_job_24:
    name: examples-rclpy-executors examples-rclcpp-multithreaded-executor examples-rclcpp-minimal-timer
      examples-rclcpp-minimal-service examples-rclcpp-minimal-publisher
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_10_job_17
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-examples-rclpy-executors ros-humble-examples-rclcpp-multithreaded-executor
        ros-humble-examples-rclcpp-minimal-timer ros-humble-examples-rclcpp-minimal-service
        ros-humble-examples-rclcpp-minimal-publisher
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-examples-rclpy-executors ros-humble-examples-rclcpp-multithreaded-executor
          ros-humble-examples-rclcpp-minimal-timer ros-humble-examples-rclcpp-minimal-service
          ros-humble-examples-rclcpp-minimal-publisher
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_11_job_25:
    name: examples-rclcpp-minimal-client action-tutorials-py
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_10_job_17
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-examples-rclcpp-minimal-client ros-humble-action-tutorials-py
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-examples-rclcpp-minimal-client ros-humble-action-tutorials-py
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_12_job_26:
    name: launch-testing-ros message-filters rosbag2-storage tf2-ros-py nav2-common
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_11_job_18
    - stage_11_job_19
    - stage_11_job_20
    - stage_11_job_21
    - stage_11_job_22
    - stage_11_job_23
    - stage_11_job_24
    - stage_11_job_25
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-launch-testing-ros ros-humble-message-filters ros-humble-rosbag2-storage
        ros-humble-tf2-ros-py ros-humble-nav2-common
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-launch-testing-ros ros-humble-message-filters
          ros-humble-rosbag2-storage ros-humble-tf2-ros-py ros-humble-nav2-common
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_12_job_27:
    name: bondcpp diagnostic-updater srdfdom hardware-interface realtime-tools
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_11_job_18
    - stage_11_job_19
    - stage_11_job_20
    - stage_11_job_21
    - stage_11_job_22
    - stage_11_job_23
    - stage_11_job_24
    - stage_11_job_25
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-bondcpp ros-humble-diagnostic-updater ros-humble-srdfdom
        ros-humble-hardware-interface ros-humble-realtime-tools
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-bondcpp ros-humble-diagnostic-updater ros-humble-srdfdom
          ros-humble-hardware-interface ros-humble-realtime-tools
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_12_job_28:
    name: ros2lifecycle-test-fixtures rqt-gui-py ros2multicast camera-info-manager
      joy
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_11_job_18
    - stage_11_job_19
    - stage_11_job_20
    - stage_11_job_21
    - stage_11_job_22
    - stage_11_job_23
    - stage_11_job_24
    - stage_11_job_25
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-ros2lifecycle-test-fixtures ros-humble-rqt-gui-py ros-humble-ros2multicast
        ros-humble-camera-info-manager ros-humble-joy
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ros2lifecycle-test-fixtures ros-humble-rqt-gui-py
          ros-humble-ros2multicast ros-humble-camera-info-manager ros-humble-joy
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_12_job_29:
    name: ros-ign-bridge turtlesim topic-monitor quality-of-service-demo-cpp examples-rclcpp-minimal-subscriber
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_11_job_18
    - stage_11_job_19
    - stage_11_job_20
    - stage_11_job_21
    - stage_11_job_22
    - stage_11_job_23
    - stage_11_job_24
    - stage_11_job_25
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-ros-ign-bridge ros-humble-turtlesim ros-humble-topic-monitor
        ros-humble-quality-of-service-demo-cpp ros-humble-examples-rclcpp-minimal-subscriber
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ros-ign-bridge ros-humble-turtlesim ros-humble-topic-monitor
          ros-humble-quality-of-service-demo-cpp ros-humble-examples-rclcpp-minimal-subscriber
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_12_job_30:
    name: examples-rclcpp-minimal-composition examples-rclcpp-minimal-action-server
      examples-rclcpp-minimal-action-client depthimage-to-laserscan action-tutorials-cpp
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_11_job_18
    - stage_11_job_19
    - stage_11_job_20
    - stage_11_job_21
    - stage_11_job_22
    - stage_11_job_23
    - stage_11_job_24
    - stage_11_job_25
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-examples-rclcpp-minimal-composition ros-humble-examples-rclcpp-minimal-action-server
        ros-humble-examples-rclcpp-minimal-action-client ros-humble-depthimage-to-laserscan
        ros-humble-action-tutorials-cpp
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-examples-rclcpp-minimal-composition ros-humble-examples-rclcpp-minimal-action-server
          ros-humble-examples-rclcpp-minimal-action-client ros-humble-depthimage-to-laserscan
          ros-humble-action-tutorials-cpp
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_13_job_31:
    name: ros2topic tf2-ros rosbag2-storage-default-plugins nav2-msgs nav2-voxel-grid
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_12_job_26
    - stage_12_job_27
    - stage_12_job_28
    - stage_12_job_29
    - stage_12_job_30
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-ros2topic ros-humble-tf2-ros ros-humble-rosbag2-storage-default-plugins
        ros-humble-nav2-msgs ros-humble-nav2-voxel-grid
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ros2topic ros-humble-tf2-ros ros-humble-rosbag2-storage-default-plugins
          ros-humble-nav2-msgs ros-humble-nav2-voxel-grid
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_13_job_32:
    name: ros2test ros2pkg ros2service ros2node image-transport
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_12_job_26
    - stage_12_job_27
    - stage_12_job_28
    - stage_12_job_29
    - stage_12_job_30
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-ros2test ros-humble-ros2pkg ros-humble-ros2service ros-humble-ros2node
        ros-humble-image-transport
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ros2test ros-humble-ros2pkg ros-humble-ros2service
          ros-humble-ros2node ros-humble-image-transport
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_13_job_33:
    name: moveit-configs-utils controller-interface control-toolbox ros2interface
      ros2doctor
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_12_job_26
    - stage_12_job_27
    - stage_12_job_28
    - stage_12_job_29
    - stage_12_job_30
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-configs-utils ros-humble-controller-interface
        ros-humble-control-toolbox ros-humble-ros2interface ros-humble-ros2doctor
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-configs-utils ros-humble-controller-interface
          ros-humble-control-toolbox ros-humble-ros2interface ros-humble-ros2doctor
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_13_job_34:
    name: ros2action rqt-console tf2-tools pcl-conversions rqt-plot
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_12_job_26
    - stage_12_job_27
    - stage_12_job_28
    - stage_12_job_29
    - stage_12_job_30
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-ros2action ros-humble-rqt-console ros-humble-tf2-tools
        ros-humble-pcl-conversions ros-humble-rqt-plot
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ros2action ros-humble-rqt-console ros-humble-tf2-tools
          ros-humble-pcl-conversions ros-humble-rqt-plot
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_13_job_35:
    name: teleop-twist-joy camera-calibration rqt-topic rqt-shell rqt-service-caller
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_12_job_26
    - stage_12_job_27
    - stage_12_job_28
    - stage_12_job_29
    - stage_12_job_30
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-teleop-twist-joy ros-humble-camera-calibration ros-humble-rqt-topic
        ros-humble-rqt-shell ros-humble-rqt-service-caller
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-teleop-twist-joy ros-humble-camera-calibration
          ros-humble-rqt-topic ros-humble-rqt-shell ros-humble-rqt-service-caller
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_13_job_36:
    name: rqt-py-console rqt-publisher rqt-graph logging-demo image-tools
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_12_job_26
    - stage_12_job_27
    - stage_12_job_28
    - stage_12_job_29
    - stage_12_job_30
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rqt-py-console ros-humble-rqt-publisher ros-humble-rqt-graph
        ros-humble-logging-demo ros-humble-image-tools
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rqt-py-console ros-humble-rqt-publisher ros-humble-rqt-graph
          ros-humble-logging-demo ros-humble-image-tools
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_13_job_37:
    name: demo-nodes-cpp-native demo-nodes-cpp composition
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_12_job_26
    - stage_12_job_27
    - stage_12_job_28
    - stage_12_job_29
    - stage_12_job_30
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-demo-nodes-cpp-native ros-humble-demo-nodes-cpp ros-humble-composition
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-demo-nodes-cpp-native ros-humble-demo-nodes-cpp
          ros-humble-composition
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_14_job_38:
    name: joint-state-publisher tf2-geometry-msgs robot-state-publisher rosbag2-cpp
      tf2-kdl
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_13_job_31
    - stage_13_job_32
    - stage_13_job_33
    - stage_13_job_34
    - stage_13_job_35
    - stage_13_job_36
    - stage_13_job_37
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-joint-state-publisher ros-humble-tf2-geometry-msgs ros-humble-robot-state-publisher
        ros-humble-rosbag2-cpp ros-humble-tf2-kdl
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-joint-state-publisher ros-humble-tf2-geometry-msgs
          ros-humble-robot-state-publisher ros-humble-rosbag2-cpp ros-humble-tf2-kdl
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_14_job_39:
    name: tf2-eigen tf2-sensor-msgs ros-testing ros2run ros2param
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_13_job_31
    - stage_13_job_32
    - stage_13_job_33
    - stage_13_job_34
    - stage_13_job_35
    - stage_13_job_36
    - stage_13_job_37
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-tf2-eigen ros-humble-tf2-sensor-msgs ros-humble-ros-testing
        ros-humble-ros2run ros-humble-ros2param
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-tf2-eigen ros-humble-tf2-sensor-msgs ros-humble-ros-testing
          ros-humble-ros2run ros-humble-ros2param
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_14_job_40:
    name: ros2lifecycle ros2launch nav2-simple-commander tf2-bullet image-proc
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_13_job_31
    - stage_13_job_32
    - stage_13_job_33
    - stage_13_job_34
    - stage_13_job_35
    - stage_13_job_36
    - stage_13_job_37
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-ros2lifecycle ros-humble-ros2launch ros-humble-nav2-simple-commander
        ros-humble-tf2-bullet ros-humble-image-proc
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ros2lifecycle ros-humble-ros2launch ros-humble-nav2-simple-commander
          ros-humble-tf2-bullet ros-humble-image-proc
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_14_job_41:
    name: rqt-msg theora-image-transport compressed-image-transport compressed-depth-image-transport
      image-view
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_13_job_31
    - stage_13_job_32
    - stage_13_job_33
    - stage_13_job_34
    - stage_13_job_35
    - stage_13_job_36
    - stage_13_job_37
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rqt-msg ros-humble-theora-image-transport ros-humble-compressed-image-transport
        ros-humble-compressed-depth-image-transport ros-humble-image-view
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rqt-msg ros-humble-theora-image-transport ros-humble-compressed-image-transport
          ros-humble-compressed-depth-image-transport ros-humble-image-view
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_14_job_42:
    name: image-publisher rqt-reconfigure rqt-image-view ros-ign-image laser-filters
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_13_job_31
    - stage_13_job_32
    - stage_13_job_33
    - stage_13_job_34
    - stage_13_job_35
    - stage_13_job_36
    - stage_13_job_37
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-image-publisher ros-humble-rqt-reconfigure ros-humble-rqt-image-view
        ros-humble-ros-ign-image ros-humble-laser-filters
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-image-publisher ros-humble-rqt-reconfigure ros-humble-rqt-image-view
          ros-humble-ros-ign-image ros-humble-laser-filters
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_14_job_43:
    name: image-common
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_13_job_31
    - stage_13_job_32
    - stage_13_job_33
    - stage_13_job_34
    - stage_13_job_35
    - stage_13_job_36
    - stage_13_job_37
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-image-common
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-image-common
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_15_job_44:
    name: joint-state-publisher-gui nav2-util rosbag2-compression rviz-common interactive-markers
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_14_job_38
    - stage_14_job_39
    - stage_14_job_40
    - stage_14_job_41
    - stage_14_job_42
    - stage_14_job_43
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-joint-state-publisher-gui ros-humble-nav2-util ros-humble-rosbag2-compression
        ros-humble-rviz-common ros-humble-interactive-markers
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-joint-state-publisher-gui ros-humble-nav2-util
          ros-humble-rosbag2-compression ros-humble-rviz-common ros-humble-interactive-markers
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_15_job_45:
    name: moveit-resources-fanuc-moveit-config warehouse-ros controller-manager sros2
      ros2component
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_14_job_38
    - stage_14_job_39
    - stage_14_job_40
    - stage_14_job_41
    - stage_14_job_42
    - stage_14_job_43
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-resources-fanuc-moveit-config ros-humble-warehouse-ros
        ros-humble-controller-manager ros-humble-sros2 ros-humble-ros2component
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-resources-fanuc-moveit-config ros-humble-warehouse-ros
          ros-humble-controller-manager ros-humble-sros2 ros-humble-ros2component
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_15_job_46:
    name: geometry2 pcl-ros stereo-image-proc image-rotate depth-image-proc
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_14_job_38
    - stage_14_job_39
    - stage_14_job_40
    - stage_14_job_41
    - stage_14_job_42
    - stage_14_job_43
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-geometry2 ros-humble-pcl-ros ros-humble-stereo-image-proc
        ros-humble-image-rotate ros-humble-depth-image-proc
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-geometry2 ros-humble-pcl-ros ros-humble-stereo-image-proc
          ros-humble-image-rotate ros-humble-depth-image-proc
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_15_job_47:
    name: rqt-srv rqt-action image-transport-plugins lifecycle dummy-robot-bringup
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_14_job_38
    - stage_14_job_39
    - stage_14_job_40
    - stage_14_job_41
    - stage_14_job_42
    - stage_14_job_43
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rqt-srv ros-humble-rqt-action ros-humble-image-transport-plugins
        ros-humble-lifecycle ros-humble-dummy-robot-bringup
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rqt-srv ros-humble-rqt-action ros-humble-image-transport-plugins
          ros-humble-lifecycle ros-humble-dummy-robot-bringup
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_16_job_48:
    name: moveit-resources-panda-moveit-config nav2-map-server nav2-lifecycle-manager
      rosbag2-compression-zstd nav-2d-utils
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_15_job_44
    - stage_15_job_45
    - stage_15_job_46
    - stage_15_job_47
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-resources-panda-moveit-config ros-humble-nav2-map-server
        ros-humble-nav2-lifecycle-manager ros-humble-rosbag2-compression-zstd ros-humble-nav-2d-utils
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-resources-panda-moveit-config ros-humble-nav2-map-server
          ros-humble-nav2-lifecycle-manager ros-humble-rosbag2-compression-zstd ros-humble-nav-2d-utils
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_16_job_49:
    name: rviz-visual-testing-framework nav2-behavior-tree joint-trajectory-controller
      nav2-amcl sros2-cmake
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_15_job_44
    - stage_15_job_45
    - stage_15_job_46
    - stage_15_job_47
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-rviz-visual-testing-framework ros-humble-nav2-behavior-tree
        ros-humble-joint-trajectory-controller ros-humble-nav2-amcl ros-humble-sros2-cmake
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-rviz-visual-testing-framework ros-humble-nav2-behavior-tree
          ros-humble-joint-trajectory-controller ros-humble-nav2-amcl ros-humble-sros2-cmake
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_16_job_50:
    name: ros2cli-common-extensions joint-state-broadcaster perception-pcl image-pipeline
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_15_job_44
    - stage_15_job_45
    - stage_15_job_46
    - stage_15_job_47
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-ros2cli-common-extensions ros-humble-joint-state-broadcaster
        ros-humble-perception-pcl ros-humble-image-pipeline
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-ros2cli-common-extensions ros-humble-joint-state-broadcaster
          ros-humble-perception-pcl ros-humble-image-pipeline
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_17_job_51:
    name: moveit-core nav2-costmap-2d rosbag2-transport rviz-default-plugins ros-core
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_16_job_48
    - stage_16_job_49
    - stage_16_job_50
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-core ros-humble-nav2-costmap-2d ros-humble-rosbag2-transport
        ros-humble-rviz-default-plugins ros-humble-ros-core
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-core ros-humble-nav2-costmap-2d ros-humble-rosbag2-transport
          ros-humble-rviz-default-plugins ros-humble-ros-core
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_18_job_52:
    name: moveit-ros-occupancy-map-monitor nav2-core rosbag2-py costmap-queue rviz2
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_17_job_51
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-ros-occupancy-map-monitor ros-humble-nav2-core
        ros-humble-rosbag2-py ros-humble-costmap-queue ros-humble-rviz2
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-ros-occupancy-map-monitor ros-humble-nav2-core
          ros-humble-rosbag2-py ros-humble-costmap-queue ros-humble-rviz2
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_18_job_53:
    name: moveit-resources-prbt-ikfast-manipulator-plugin moveit-simple-controller-manager
      nav2-rviz-plugins pilz-industrial-motion-planner-testutils
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_17_job_51
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-resources-prbt-ikfast-manipulator-plugin ros-humble-moveit-simple-controller-manager
        ros-humble-nav2-rviz-plugins ros-humble-pilz-industrial-motion-planner-testutils
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-resources-prbt-ikfast-manipulator-plugin
          ros-humble-moveit-simple-controller-manager ros-humble-nav2-rviz-plugins
          ros-humble-pilz-industrial-motion-planner-testutils
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_19_job_54:
    name: moveit-ros-planning dwb-core ros2bag nav2-regulated-pure-pursuit-controller
      nav2-controller
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_18_job_52
    - stage_18_job_53
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-ros-planning ros-humble-dwb-core ros-humble-ros2bag
        ros-humble-nav2-regulated-pure-pursuit-controller ros-humble-nav2-controller
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-ros-planning ros-humble-dwb-core ros-humble-ros2bag
          ros-humble-nav2-regulated-pure-pursuit-controller ros-humble-nav2-controller
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_19_job_55:
    name: nav2-waypoint-follower nav2-theta-star-planner nav2-smoother nav2-smac-planner
      nav2-planner
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_18_job_52
    - stage_18_job_53
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-nav2-waypoint-follower ros-humble-nav2-theta-star-planner
        ros-humble-nav2-smoother ros-humble-nav2-smac-planner ros-humble-nav2-planner
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-nav2-waypoint-follower ros-humble-nav2-theta-star-planner
          ros-humble-nav2-smoother ros-humble-nav2-smac-planner ros-humble-nav2-planner
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_19_job_56:
    name: nav2-navfn-planner nav2-bt-navigator nav2-behaviors rqt-bag ros-ign-gazebo-demos
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_18_job_52
    - stage_18_job_53
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-nav2-navfn-planner ros-humble-nav2-bt-navigator ros-humble-nav2-behaviors
        ros-humble-rqt-bag ros-humble-ros-ign-gazebo-demos
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-nav2-navfn-planner ros-humble-nav2-bt-navigator
          ros-humble-nav2-behaviors ros-humble-rqt-bag ros-humble-ros-ign-gazebo-demos
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_19_job_57:
    name: moveit-plugins
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_18_job_52
    - stage_18_job_53
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-plugins
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-plugins
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_20_job_58:
    name: moveit-kinematics dwb-plugins dwb-critics rosbag2-tests moveit-ros-warehouse
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_19_job_54
    - stage_19_job_55
    - stage_19_job_56
    - stage_19_job_57
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-kinematics ros-humble-dwb-plugins ros-humble-dwb-critics
        ros-humble-rosbag2-tests ros-humble-moveit-ros-warehouse
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-kinematics ros-humble-dwb-plugins ros-humble-dwb-critics
          ros-humble-rosbag2-tests ros-humble-moveit-ros-warehouse
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_20_job_59:
    name: moveit-planners-ompl nav2-rotation-shim-controller moveit-ros-robot-interaction
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_19_job_54
    - stage_19_job_55
    - stage_19_job_56
    - stage_19_job_57
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-planners-ompl ros-humble-nav2-rotation-shim-controller
        ros-humble-moveit-ros-robot-interaction
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-planners-ompl ros-humble-nav2-rotation-shim-controller
          ros-humble-moveit-ros-robot-interaction
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_21_job_60:
    name: moveit-ros-move-group nav2-dwb-controller rosbag2 moveit-ros-benchmarks
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_20_job_58
    - stage_20_job_59
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-ros-move-group ros-humble-nav2-dwb-controller
        ros-humble-rosbag2 ros-humble-moveit-ros-benchmarks
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-ros-move-group ros-humble-nav2-dwb-controller
          ros-humble-rosbag2 ros-humble-moveit-ros-benchmarks
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_22_job_61:
    name: moveit-resources-prbt-moveit-config moveit-ros-planning-interface navigation2
      rqt-bag-plugins ros-base
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_21_job_60
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-resources-prbt-moveit-config ros-humble-moveit-ros-planning-interface
        ros-humble-navigation2 ros-humble-rqt-bag-plugins ros-humble-ros-base
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-resources-prbt-moveit-config ros-humble-moveit-ros-planning-interface
          ros-humble-navigation2 ros-humble-rqt-bag-plugins ros-humble-ros-base
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_23_job_62:
    name: moveit-resources-prbt-pg70-support moveit-servo moveit-ros-visualization
      rqt-common-plugins simulation
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_22_job_61
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-resources-prbt-pg70-support ros-humble-moveit-servo
        ros-humble-moveit-ros-visualization ros-humble-rqt-common-plugins ros-humble-simulation
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-resources-prbt-pg70-support ros-humble-moveit-servo
          ros-humble-moveit-ros-visualization ros-humble-rqt-common-plugins ros-humble-simulation
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_23_job_63:
    name: perception
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_22_job_61
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-perception
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-perception
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_24_job_64:
    name: pilz-industrial-motion-planner moveit-ros desktop
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_23_job_62
    - stage_23_job_63
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-pilz-industrial-motion-planner ros-humble-moveit-ros
        ros-humble-desktop
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-pilz-industrial-motion-planner ros-humble-moveit-ros
          ros-humble-desktop
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
  stage_25_job_65:
    name: moveit-planners desktop-full moveit
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    needs:
    - stage_24_job_64
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-humble-moveit-planners ros-humble-desktop-full ros-humble-moveit
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-moveit-planners ros-humble-desktop-full ros-humble-moveit
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_osx.sh
on:
  push:
    branches:
    - buildbranch_osx
