name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: pull_request
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: |
      if [git diff --name-only]
