name: GitHub Actions Demo
run-name: Running AI Patcher Verifier! 🚀
on: [pull_request]

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "Running AI Patch Checker Workflow!"


      - uses: actions/checkout@v3


      - run: python .scripts/run_patch_workflow.py --ip ${{ secrets.LLM_IP }} -s ${{ secrets.SKIP_EXISTING_DIR }}

      - name: commiter on success
        if: ${{success()}}
        uses: stefanzweifel/git-auto-commit-action@v4

